server:
  host: "0.0.0.0"
  port: 25

smtp:
  hostname: "localhost"
  max_size: 10485760      # 10MB
  max_recipients: 100

storage:
  path: "./maildata"

tls:
  enabled: false
  cert_file: "./certs/server.crt"
  key_file: "./certs/server.key"
