server:
  host: "127.0.0.1"
  port: 2525
  instance_name: "smtpd-dev" # 用于生成唯一的邮件 ID

smtp:
  hostname: "localhost"
  max_size: 10485760 # 10MB in bytes
  max_recipients: 100
  auth_file: "./auth.txt"
  allow_anonymous: false
  allow_insecure_auth: true # 允许非 TLS 认证

storage:
  path: "./maildata"

tls:
  enabled: false # 禁用 TLS
  cert_file: "./certs/server.crt"
  key_file: "./certs/server.key"

log:
  level: "info" # 日志级别：debug, info, warn, error
  format: "text" # 日志格式：text, json
  file: "./logs/smtpd.log" # 日志文件路径，为空则输出到标准输出
  add_source: true # 是否添加源代码位置
