server:
  host: "127.0.0.1"
  port: 2525
  instance_name: "smtpd-dev"  # Used for generating unique mail IDs

smtp:
  hostname: "localhost"
  max_size: 10485760      # 10MB
  max_recipients: 100

storage:
  path: "./maildata"

tls:
  enabled: true
  cert_file: "./certs/server.crt"
  key_file: "./certs/server.key"
